# Site settings
title: Gowtham GTS
author: Gowtham Gopalakrishnan
description: > # this means to ignore newlines until "baseurl:"
  Code | Design | Gaming | Music | FOSS
# baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "https://gowtham.dev" # the base hostname & protocol for your site
permalink: "/blog/:title:output_ext"
twitter_username: gowthamgts
github_username:  gowthamgts

# Build settings
markdown: kramdown
exclude: [node_modules, Gruntfile.js, package.json]
